# Tibble containing the abbreviations and names of the landscape metrics


lsm_abbreviations_names <- tibble::tibble(
    metric = c(
        "area",
        "perim",
        "gyrate",
        "ca",
        "pland",
        "lpi",
        "te",
        "ed",
        "area_mn",
        "area_sd",
        "area_cv",
        "gyrate_mn",
        "gyrate_sd",
        "gyrate_cv",
        "ta",

        "para",
        "shape",
        "frac",
        "circle",
        "contig",
        "pafrac",
        "para_mn",
        "para_sd",
        "para_cv",
        "shape_mn",
        "shape_sd",
        "shape_cv",
        "frac_mn",
        "frac_sd",
        "frac_cv",
        "circle_mn",
        "circle_sd",
        "circle_cv",
        "contig_mn",
        "contig_sd",
        "contig_cv",

        "core",
        "ncore",
        "cai",
        "tca",
        "cpland",
        "ndca",
        "dcad",
        "core_mn",
        "core_sd",
        "core_cv",
        "dcore_mn",
        "dcore_sd",
        "dcore_cv",
        "cai_mn",
        "cai_sd",
        "cai_cv",
        "tca",

        "enn",
        "pladj",
        "ai",
        "clumpy",
        "lsi",
        "cohesion",
        "np",
        "pd",
        "division",
        "split",
        "mesh",
        "enn_mn",
        "enn_sd",
        "enn_cv",

        "pr",
        "prd",
        "rpr",
        "shdi",
        "sidi",
        "msidi",
        "shei",
        "siei",
        "msiei",

        "ent",
        "joinent",
        "mutinf",
        "condent"
    ),

    full_name = c(
        "patch area",
        "patch perimeter",
        "radius of gyration",
        "total (class) area",
        "percentage of landscape",
        "largest patch index",
        "total edge",
        "edge density",
        "patch area distribution (mean)",
        "patch area distribution (standard deviation)",
        "patch area distribution (coeffiecent of variation)",
        "radius of gyration distribution (mean)",
        "radius of gyration distribution (standard deviation)",
        "radius of gyration distribution (coeffiecent of variation)",
        "total area",

        "perimeter-area ratio",
        "shape index",
        "fractal dimension index",
        "related circumscribing circle",
        "contiguity index",
        "perimeter-area fractal dimension",
        "perimeter-area ratio distribution (mean)",
        "perimeter-area ratio distribution (standard deviation)",
        "perimeter-area ratio distribution (coeffiecent of variation)",
        "shape index distribution (mean)",
        "shape index distribution (standard deviation)",
        "shape index distribution (coeffiecent of variation)",
        "fractal index distribution (mean)",
        "fractal index distribution (standard deviation)",
        "fractal index distribution (coeffiecent of variation)",
        "related circumscribing circle distribution (mean)",
        "related circumscribing circle distribution (standard deviation)",
        "related circumscribing circle distribution (coeffiecent of variation)",
        "contiguity index distribution (mean)",
        "contiguity index distribution (standard deviation)",
        "contiguity index distribution (coeffiecent of variation)",

        "core area",
        "number of core areas",
        "core area index",
        "total core area",
        "core area percentag of landscape",
        "number of disjunct core areas",
        "disjunct core area density",
        "core area distribution (mean)",
        "core area distribution (standard deviation)",
        "core area distribution (coeffiecent of variation)",
        "disjunct core area distribution (mean)",
        "disjunct core area distribution (standard deviation)",
        "disjunct core area distribution (coeffiecent of variation)",
        "core area index distribution (mean)",
        "core area index distribution (standard deviation)",
        "core area index distribution (coeffiecent of variation)",
        "total core area",

        "euclidean nearest neighbor distance",
        "percentage of like adjacencies",
        "aggregation index",
        "clumpiness index",
        "landscape shape index",
        "patch cohesion index",
        "number of patches",
        "patch density",
        "landscape division index",
        "splitting index",
        "Effective mesh size",
        "euclidean nearest neighbor distance distribution (mean)",
        "euclidean nearest neighbor distance distribution (standard deviation)",
        "euclidean nearest neighbor distance distribution (coeffiecent of variation)",

        "patch richness",
        "patch richness density",
        "relative patch richness",
        "shannon's diversity index",
        "simpson's diversity index",
        "modified simpson's diversity index",
        "shannon's evenness index",
        "simspon's evenness index",
        "modified simpson's evenness index",

        "shannon entropy",
        "joint entropy",
        "mutual information",
        "conditional entropy"
        ),


    type = c(
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",
        "area and ege metric",

        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",

        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",

        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",

        "diversity metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",

        "new metric",
        "new metric",
        "new metric",
        "new metric"
    )
)

devtools::use_data(lsm_abbreviations_names, overwrite = TRUE)
