library(usethis)

# Tibble containing the abbreviations and names of the landscape metrics

lsm_abbreviations_names <- tibble::tibble(

    metric = c(
        # patch level
        "area",
        "cai",
        "circle",
        "contig",
        "core",
        "enn",
        "frac",
        "gyrate",
        "ncore",
        "para",
        "perim",
        "shape",

        # class level
        "ai",
        "area_cv",
        "area_mn",
        "area_sd",
        "ca",
        "cai_cv",
        "cai_mn",
        "cai_sd",
        "circle_cv",
        "circle_mn",
        "circle_sd",
        "clumpy",
        "cohesion",
        "contig_cv",
        "contig_mn",
        "contig_sd",
        "core_cv",
        "core_mn",
        "core_sd",
        "cpland",
        "dcad",
        "dcore_cv",
        "dcore_mn",
        "dcore_sd",
        "division",
        "ed",
        "enn_cv",
        "enn_mn",
        "enn_sd",
        "frac_cv",
        "frac_mn",
        "frac_sd",
        "gyrate_cv",
        "gyrate_mn",
        "gyrate_sd",
        "iji",
        "lpi",
        "lsi",
        "mesh",
        "ndca",
        "nlsi",
        "np",
        "pafrac",
        "para_cv",
        "para_mn",
        "para_sd",
        "pd",
        "pladj",
        "pland",
        "shape_cv",
        "shape_mn",
        "shape_sd",
        "split",
        "tca",
        "te",

        # landscape level
        "ai",
        "area_cv",
        "area_mn",
        "area_sd",
        "cai_cv",
        "cai_mn",
        "cai_sd",
        "circle_cv",
        "circle_mn",
        "circle_sd",
        "cohesion",
        "condent",
        "contag",
        "contig_cv",
        "contig_mn",
        "contig_sd",
        "core_cv",
        "core_mn",
        "core_sd",
        "dcad",
        "dcore_cv",
        "dcore_mn",
        "dcore_sd",
        "division",
        "ed",
        "enn_cv",
        "enn_mn",
        "enn_sd",
        "ent",
        "frac_cv",
        "frac_mn",
        "frac_sd",
        "gyrate_cv",
        "gyrate_mn",
        "gyrate_sd",
        "iji",
        "joinent",
        "lpi",
        "lsi",
        "mesh",
        "msidi",
        "msiei",
        "mutinf",
        "ndca",
        "np",
        "pafrac",
        "para_cv",
        "para_mn",
        "para_sd",
        "pd",
        "pladj",
        "pr",
        "prd",
        "relmutinf",
        "rpr",
        "shape_cv",
        "shape_mn",
        "shape_sd",
        "shdi",
        "shei",
        "sidi",
        "siei",
        "split",
        "ta",
        "tca",
        "te"
    ),

    name = c(

        # patch level
        "patch area",
        "core area index",
        "related circumscribing circle",
        "contiguity index",
        "core area",
        "euclidean nearest neighbor distance",
        "fractal dimension index",
        "radius of gyration",
        "number of core areas",
        "perimeter-area ratio",
        "patch perimeter",
        "shape index",

        # class level
        "aggregation index",
        "patch area",
        "patch area",
        "patch area",
        "total (class) area",
        "core area index",
        "core area index",
        "core area index",
        "related circumscribing circle",
        "related circumscribing circle",
        "related circumscribing circle",
        "clumpiness index",
        "patch cohesion index",
        "contiguity index",
        "contiguity index",
        "contiguity index",
        "core area",
        "core area",
        "core area",
        "core area percentage of landscape",
        "disjunct core area density",
        "disjunct core area",
        "disjunct core area",
        "disjunct core area",
        "division index",
        "edge density",
        "euclidean nearest neighbor distance",
        "euclidean nearest neighbor distance",
        "euclidean nearest neighbor distance",
        "fractal dimension index",
        "fractal dimension index",
        "fractal dimension index",
        "radius of gyration",
        "radius of gyration",
        "radius of gyration",
        "interspersion and juxtaposition index",
        "largest patch index",
        "landscape shape index",
        "effective mesh size",
        "number of disjunct core areas",
        "normalized landscape shape index",
        "number of patches",
        "perimeter-area fractal dimension",
        "perimeter-area ratio",
        "perimeter-area ratio",
        "perimeter-area ratio",
        "patch density",
        "percentage of like adjacencies",
        "percentage of landscape",
        "shape index",
        "shape index",
        "shape index",
        "splitting index",
        "total core area",
        "total edge",

        # landscape level
        "aggregation index",
        "patch area",
        "patch area",
        "patch area",
        "core area index",
        "core area index",
        "core area index",
        "related circumscribing circle",
        "related circumscribing circle",
        "related circumscribing circle",
        "patch cohesion index",
        "conditional entropy",
        "connectance",
        "contiguity index",
        "contiguity index",
        "contiguity index",
        "core area",
        "core area",
        "core area",
        "disjunct core area density",
        "disjunct core area",
        "disjunct core area",
        "disjunct core area",
        "division index",
        "edge density",
        "euclidean nearest neighbor distance",
        "euclidean nearest neighbor distance",
        "euclidean nearest neighbor distance",
        "shannon entropy",
        "fractal dimension index",
        "fractal dimension index",
        "fractal dimension index",
        "radius of gyration",
        "radius of gyration",
        "radius of gyration",
        "interspersion and juxtaposition index",
        "joint entropy",
        "largest patch index",
        "landscape shape index",
        "effective mesh size",
        "modified simpson's diversity index",
        "modified simpson's evenness index",
        "mutual information",
        "number of disjunct core areas",
        "number of patches",
        "perimeter-area fractal dimension",
        "perimeter-area ratio",
        "perimeter-area ratio",
        "perimeter-area ratio",
        "patch density",
        "percentage of like adjacencies",
        "patch richness",
        "patch richness density",
        "relative mutual information",
        "relative patch richness",
        "shape index",
        "shape index",
        "shape index",
        "shannon's diversity index",
        "shannon's evenness index",
        "simpson's diversity index",
        "simspon's evenness index",
        "splitting index",
        "total area",
        "total core area",
        "total edge"
    ),


    type = c(

        # patch level
        "area and edge metric",
        "core area metric",
        "shape metric",
        "shape metric",
        "core area metric",
        "aggregation metric",
        "shape metric",
        "area and edge metric",
        "core area metric",
        "shape metric",
        "area and edge metric",
        "shape metric",

        # class level
        "aggregation metric",
        "area and edge metric",
        "area and edge metric",
        "area and edge metric",
        "area and edge metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "aggregation metric",
        "aggregation metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "aggregation metric",
        "area and edge metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "area and edge metric",
        "area and edge metric",
        "area and edge metric",
        "aggregation metric",
        "area and edge metric",
        "aggregation metric",
        "aggregation metric",
        "core area metric",
        "aggregation metric",
        "aggregation metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "aggregation metric",
        "aggregation metric",
        "area and edge metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "aggregation metric",
        "core area metric",
        "area and edge metric",

        # landscape level
        "aggregation metric",
        "area and edge metric",
        "area and edge metric",
        "area and edge metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "aggregation metric",
        "complexity metric",
        "aggregation metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "core area metric",
        "aggregation metric",
        "area and edge metric",
        "aggregation metric",
        "aggregation metric",
        "aggregation metric",
        "complexity metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "area and edge metric",
        "area and edge metric",
        "area and edge metric",
        "aggregation metric",
        "complexity metric",
        "area and edge metric",
        "aggregation metric",
        "aggregation metric",
        "diversity metric",
        "diversity metric",
        "complexity metric",
        "core area metric",
        "aggregation metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "aggregation metric",
        "aggregation metric",
        "diversity metric",
        "diversity metric",
        "complexity metric",
        "diversity metric",
        "shape metric",
        "shape metric",
        "shape metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",
        "diversity metric",
        "aggregation metric",
        "area and edge metric",
        "core area metric",
        "area and edge metric"
    ),

    level = c(

        # patch level
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",
        "patch",

        # class level
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",
        "class",

        # landscape level
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape",
        "landscape"
    ),

    function_name = c(

        # patch level
        "lsm_p_area",
        "lsm_p_cai",
        "lsm_p_circle",
        "lsm_p_contig",
        "lsm_p_core",
        "lsm_p_enn",
        "lsm_p_frac",
        "lsm_p_gyrate",
        "lsm_p_ncore",
        "lsm_p_para",
        "lsm_p_perim",
        "lsm_p_shape",

        # class level
        "lsm_c_ai",
        "lsm_c_area_cv",
        "lsm_c_area_mn",
        "lsm_c_area_sd",
        "lsm_c_ca",
        "lsm_c_cai_cv",
        "lsm_c_cai_mn",
        "lsm_c_cai_sd",
        "lsm_c_circle_cv",
        "lsm_c_circle_mn",
        "lsm_c_circle_sd",
        "lsm_c_clumpy",
        "lsm_c_cohesion",
        "lsm_c_contig_cv",
        "lsm_c_contig_mn",
        "lsm_c_contig_sd",
        "lsm_c_core_cv",
        "lsm_c_core_mn",
        "lsm_c_core_sd",
        "lsm_c_cpland",
        "lsm_c_dcad",
        "lsm_c_dcore_cv",
        "lsm_c_dcore_mn",
        "lsm_c_dcore_sd",
        "lsm_c_division",
        "lsm_c_ed",
        "lsm_c_enn_cv",
        "lsm_c_enn_mn",
        "lsm_c_enn_sd",
        "lsm_c_frac_cv",
        "lsm_c_frac_mn",
        "lsm_c_frac_sd",
        "lsm_c_gyrate_cv",
        "lsm_c_gyrate_mn",
        "lsm_c_gyrate_sd",
        "lsm_c_iji",
        "lsm_c_lpi",
        "lsm_c_lsi",
        "lsm_c_mesh",
        "lsm_c_ndca",
        "lsm_c_nlsi",
        "lsm_c_np",
        "lsm_c_pafrac",
        "lsm_c_para_cv",
        "lsm_c_para_mn",
        "lsm_c_para_sd",
        "lsm_c_pd",
        "lsm_c_pladj",
        "lsm_c_pland",
        "lsm_c_shape_cv",
        "lsm_c_shape_mn",
        "lsm_c_shape_sd",
        "lsm_c_split",
        "lsm_c_tca",
        "lsm_c_te",

        # landscape level
        "lsm_l_ai",
        "lsm_l_area_cv",
        "lsm_l_area_mn",
        "lsm_l_area_sd",
        "lsm_l_cai_cv",
        "lsm_l_cai_mn",
        "lsm_l_cai_sd",
        "lsm_l_circle_cv",
        "lsm_l_circle_mn",
        "lsm_l_circle_sd",
        "lsm_l_cohesion",
        "lsm_l_condent",
        "lsm_l_contag",
        "lsm_l_contig_cv",
        "lsm_l_contig_mn",
        "lsm_l_contig_sd",
        "lsm_l_core_cv",
        "lsm_l_core_mn",
        "lsm_l_core_sd",
        "lsm_l_dcad",
        "lsm_l_dcore_cv",
        "lsm_l_dcore_mn",
        "lsm_l_dcore_sd",
        "lsm_l_division",
        "lsm_l_ed",
        "lsm_l_enn_cv",
        "lsm_l_enn_mn",
        "lsm_l_enn_sd",
        "lsm_l_ent",
        "lsm_l_frac_cv",
        "lsm_l_frac_mn",
        "lsm_l_frac_sd",
        "lsm_l_gyrate_cv",
        "lsm_l_gyrate_mn",
        "lsm_l_gyrate_sd",
        "lsm_l_iji",
        "lsm_l_joinent",
        "lsm_l_lpi",
        "lsm_l_lsi",
        "lsm_l_mesh",
        "lsm_l_msidi",
        "lsm_l_msiei",
        "lsm_l_mutinf",
        "lsm_l_ndca",
        "lsm_l_np",
        "lsm_l_pafrac",
        "lsm_l_para_cv",
        "lsm_l_para_mn",
        "lsm_l_para_sd",
        "lsm_l_pd",
        "lsm_l_pladj",
        "lsm_l_pr",
        "lsm_l_prd",
        "lsm_l_relmutinf",
        "lsm_l_rpr",
        "lsm_l_shape_cv",
        "lsm_l_shape_mn",
        "lsm_l_shape_sd",
        "lsm_l_shdi",
        "lsm_l_shei",
        "lsm_l_sidi",
        "lsm_l_siei",
        "lsm_l_split",
        "lsm_l_ta",
        "lsm_l_tca",
        "lsm_l_te"
    )
)

usethis::use_data(lsm_abbreviations_names, overwrite = TRUE)
