# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title 8-way connectedness border states.
#'
#' @description 8-way neighborhood connected component border
#' (edge/vertice) states.
#'
#' @param m A two dimensional numeric matrix.
#'
#' @return Numeric matrix of the same dimensions as mat with
#' values indicating 8-way connected border states.
#'
#' @details A cell is considered to have 8 distinct borders indexed
#' in counter clockwise order with values of 2^c(0:7) beginning
#' with the North edge and ending with the Northeast vertex. A cell
#' fully enclosed by similar neighbors has no borders ( a 0 value )
#' whereas when fully enclosed by dissimilar neighbors is fully
#' bordered ( a 255 value ).
#'
#' @author Thell Fowler \email{thell@tbfowler.name}
#'
#' @keywords internal
#'
#' @name ccl_borders
#' @export
ccl_borders <- function(m) {
    .Call('_landscapemetrics_ccl_borders', PACKAGE = 'landscapemetrics', m)
}

rcpp_xy_from_matrix <- function(x) {
    .Call('_landscapemetrics_rcpp_xy_from_matrix', PACKAGE = 'landscapemetrics', x)
}

rcpp_cell_from_xy <- function(x, y) {
    .Call('_landscapemetrics_rcpp_cell_from_xy', PACKAGE = 'landscapemetrics', x, y)
}

rcpp_get_adjacency <- function(x, directions) {
    .Call('_landscapemetrics_rcpp_get_adjacency', PACKAGE = 'landscapemetrics', x, directions)
}

rcpp_get_pairs <- function(x, directions = 4L) {
    .Call('_landscapemetrics_rcpp_get_pairs', PACKAGE = 'landscapemetrics', x, directions)
}

rcpp_get_composition_vector <- function(x) {
    .Call('_landscapemetrics_rcpp_get_composition_vector', PACKAGE = 'landscapemetrics', x)
}

rcpp_get_coocurrence_matrix <- function(x, directions = 4L) {
    .Call('_landscapemetrics_rcpp_get_coocurrence_matrix', PACKAGE = 'landscapemetrics', x, directions)
}

triangular_index <- function(r, c) {
    .Call('_landscapemetrics_triangular_index', PACKAGE = 'landscapemetrics', r, c)
}

rcpp_get_coocurrence_vector <- function(x, directions = 8L, ordered = TRUE) {
    .Call('_landscapemetrics_rcpp_get_coocurrence_vector', PACKAGE = 'landscapemetrics', x, directions, ordered)
}

rcpp_get_offdiagonal_vector <- function(x, directions = 8L) {
    .Call('_landscapemetrics_rcpp_get_offdiagonal_vector', PACKAGE = 'landscapemetrics', x, directions)
}

rcpp_get_entropy <- function(x, base = "log2") {
    .Call('_landscapemetrics_rcpp_get_entropy', PACKAGE = 'landscapemetrics', x, base)
}

#' @title 8-way connected component labelling.
#'
#' @description 8-way neighborhood connected component labelling of
#' all given values.
#'
#' @param m A two dimensional numeric matrix.
#'
#' @return Numeric matrix of the same dimensions as mat with
#'   values indicating component identification label where values
#'   increase in column major order.
#'
#' @author Thell Fowler \email{thell@tbfowler.name}
#'
#' @keywords internal
#'
#' @name ccl_labels
#' @export
ccl_labels <- function(m) {
    .Call('_landscapemetrics_ccl_labels', PACKAGE = 'landscapemetrics', m)
}

timesTwo <- function(x) {
    .Call('_landscapemetrics_timesTwo', PACKAGE = 'landscapemetrics', x)
}

doXYFromCell <- function(x) {
    .Call('_landscapemetrics_doXYFromCell', PACKAGE = 'landscapemetrics', x)
}

doCrossTab2 <- function(x, y) {
    .Call('_landscapemetrics_doCrossTab2', PACKAGE = 'landscapemetrics', x, y)
}

