# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title 8-way connectedness border states.
#'
#' @description 8-way neighborhood connected component border
#' (edge/vertice) states.
#'
#' @param m A two dimensional numeric matrix.
#'
#' @return Numeric matrix of the same dimensions as mat with
#' values indicating 8-way connected border states.
#'
#' @details A cell is considered to have 8 distinct borders indexed
#' in counter clockwise order with values of 2^c(0:7) beginning
#' with the North edge and ending with the Northeast vertex. A cell
#' fully enclosed by similar neighbors has no borders ( a 0 value )
#' whereas when fully enclosed by dissimilar neighbors is fully
#' bordered ( a 255 value ).
#'
#' @author Thell Fowler \email{thell@tbfowler.name}
#'
#' @keywords internal
#'
#' @name ccl_borders
#' @export
ccl_borders <- function(m) {
    .Call('_landscapemetrics_ccl_borders', PACKAGE = 'landscapemetrics', m)
}

#' Coordinates from a matrix
#'
#' This function gets coordinates (row and column numbers) of the matrix cells.
#'
#' @param x A matrix
#' @param cell A vector of cell number.
#' If NULL, the coordinates will be calculated for the whole matrix
rcpp_xy_from_matrix <- function(x, cell = NULL) {
    .Call('_landscapemetrics_rcpp_xy_from_matrix', PACKAGE = 'landscapemetrics', x, cell)
}

#' Get cell number
#'
#' Get cell number(s) of a matrix from row and column numbers.
#' Cell numbers start at 0 in the upper left corner,
#' and increase from top to bottom, and then from left to right.
#'
#' @param x A matrix
#' @param y A matrix with two columns (row and column numbers)
rcpp_cell_from_xy <- function(x, y) {
    .Call('_landscapemetrics_rcpp_cell_from_xy', PACKAGE = 'landscapemetrics', x, y)
}

#' Create neighborhood coordinates
#'
#' This function creates a neighborhood coordinates matrix based on the directions parameter.
#'
#' @param directions The number of directions in which cells should be connected:
#' 4 (rook's case), 8 (queen's case), or a neigborhood matrix.
#' The neigborhood matrix should have one cell with value 0 (the focal cell),
#' and at least one cell with value 1 (the adjacent cells).
#' Cells with other values (e.g. NA) are ignored.
rcpp_create_neighborhood <- function(directions) {
    .Call('_landscapemetrics_rcpp_create_neighborhood', PACKAGE = 'landscapemetrics', directions)
}

#' Adjacent cells
#'
#' Identify cells that are adjacent to a set of cells on a matrix.
#' An output is a two columns matrix, where the first column contains a
#' main cell number and the second column contains an adjacent cell number.
#'
#' @param x A matrix
#' @param directions The number of directions in which cells should be connected:
#' 4 (rook's case), 8 (queen's case), or a neigborhood matrix.
#' The neigborhood matrix should have one cell with value 0 (the focal cell),
#' and at least one cell with value 1 (the adjacent cells).
#' Cells with other values (e.g. NA) are ignored.
rcpp_get_adjacency <- function(x, directions) {
    .Call('_landscapemetrics_rcpp_get_adjacency', PACKAGE = 'landscapemetrics', x, directions)
}

#' Adjacent cells values
#'
#' Extract values of adjacent cells.
#' An output is a two columns matrix, where the first column contains a
#' main cell value and the second column contains an adjacent cell value.
#'
#' @param x A matrix
#' @param directions The number of directions in which cells should be connected:
#' 4 (rook's case), 8 (queen's case), or a neigborhood matrix.
#' The neigborhood matrix should have one cell with value 0 (the focal cell),
#' and at least one cell with value 1 (the adjacent cells).
#' Cells with other values (e.g. NA) are ignored.
rcpp_get_pairs <- function(x, directions) {
    .Call('_landscapemetrics_rcpp_get_pairs', PACKAGE = 'landscapemetrics', x, directions)
}

rcpp_get_composition_vector <- function(x) {
    .Call('_landscapemetrics_rcpp_get_composition_vector', PACKAGE = 'landscapemetrics', x)
}

rcpp_get_coocurrence_matrix <- function(x, directions) {
    .Call('_landscapemetrics_rcpp_get_coocurrence_matrix', PACKAGE = 'landscapemetrics', x, directions)
}

triangular_index <- function(r, c) {
    .Call('_landscapemetrics_triangular_index', PACKAGE = 'landscapemetrics', r, c)
}

rcpp_get_coocurrence_vector <- function(x, directions, ordered = TRUE) {
    .Call('_landscapemetrics_rcpp_get_coocurrence_vector', PACKAGE = 'landscapemetrics', x, directions, ordered)
}

rcpp_get_offdiagonal_vector <- function(x, directions) {
    .Call('_landscapemetrics_rcpp_get_offdiagonal_vector', PACKAGE = 'landscapemetrics', x, directions)
}

rcpp_get_entropy <- function(x, base = "log2") {
    .Call('_landscapemetrics_rcpp_get_entropy', PACKAGE = 'landscapemetrics', x, base)
}

#' @title 8-way connected component labelling.
#'
#' @description 8-way neighborhood connected component labelling of
#' all given values.
#'
#' @param m A two dimensional numeric matrix.
#'
#' @return Numeric matrix of the same dimensions as mat with
#'   values indicating component identification label where values
#'   increase in column major order.
#'
#' @author Thell Fowler \email{thell@tbfowler.name}
#'
#' @keywords internal
#'
#' @name ccl_labels
#' @export
ccl_labels <- function(m) {
    .Call('_landscapemetrics_ccl_labels', PACKAGE = 'landscapemetrics', m)
}

